.TH "circular-main-menu" "1" "2013-02-25" "inne" "Circular-Application-Menu"
.SH NAME
circular-main-menu - Circular-Main-Menu for the GNOME desktop
.SH SYNOPSIS
circular-main-menu [OPTION ...]
.SH DESCRIPTION
The circular-main-menu(1) command is just a link to cmm(1). See the manpage of cmm(1) for more information.
.SH SEE ALSO
\fBcmm(1)\fR
